### ISSUE TITLE
BIG PROBLem

### ISSUE THREAD

**Issue by matthewmargolin** [Tom60chat/MultiplayerFPS-Tutorial#3]
I am trying to set this up following brackeys tutorial and I don't wanna just copy and paste so is there a way i could just implement the stuff from episodes 17-21?

**Comment by Tom60chat** [comment]
The Brackeys tutorial is so old, I don't really remember the implementations, but what you could do is compare the file that Brakeys makes and the same in the repository.
If you want a more recent tutorial I can recommend FirstGearGame to you: https://www.youtube.com/c/FirstGearGames/videos
